export const SET_USER = "SET_USER"
export const SET_LOADING = "SET_LOADING"
export const SET_POPUP = "SET_POPUP"

export const GABT = "GABT"
export const CNI = "CNI"
export const UIBIAD = "UIBIAD"
export const RIBI = "RIBI"
export const CAP = "CAP"
export const CAI = "CAI"
export const GAP = "GAP"
export const CPFB64 = "CPFB64"