export const SET_USER = "SET_USER"
export const SET_LOADING = "SET_LOADING"
export const SET_ACTIVE_PAGE  = "SET_ACTIVE_PAGE_ID"
export const PAGE_SIZE  = "PAGE_SIZE"
export const SET_TASKS  = "SET_TASKS"
export const NEW_TASK  = "NEW_TASKS"
export const DESCRIPTION  = "DESCRIPTION"
export const COMPLETE  = "COMPLETE"
export const ACTIVE_FILTER  = "ACTIVE_FILTER"


export const GABT = "GABT"
export const CNI = "CNI"
export const UIBIAD = "UIBIAD"
export const RIBI = "RIBI"
export const CAP = "CAP"
export const CAI = "CAI"
